name: Build Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Cài đặt Trình biên dịch Đồ họa (GCC)
      uses: msys2/setup-msys2@v2
      with:
        msys2-location: 'C:\msys64'
        install: >-
          mingw-w64-x86_64-gcc

    - name: Biên dịch file .exe
      run: |
        $env:PATH = "C:\msys64\mingw64\bin;" + $env:PATH
        $env:CGO_ENABLED = "1"
        go mod tidy
        go build -ldflags="-H windowsgui" -o OutlierFinder.exe main.go

    - name: Lưu trữ sản phẩm
      uses: actions/upload-artifact@v4
      with:
        name: OutlierFinder-Windows
        path: OutlierFinder.exe
